export const tips = {
  tr: [
    "Kod yazarken küçük ve test edilebilir parçalar oluşturun.",
    "Daha iyi bir geliştirici olmak için her gün bir şey öğrenin.",
    "Yazılım sadece kod yazmak değildir; problem çözme sanatıdır.",
    "Her kod parçasını belgelendirmeye özen gösterin.",
    "Başarı, her gün atılan küçük adımlarla gelir.",
    "Hatırlayın: Kod tekrar yazılmak için vardır, kutsal değildir!",
    "Bir hata bulmak, bir çözüm üretmenin başlangıcıdır.",
    "Bir problem mi var? Önce Google, sonra mentorlar!",
    "Kod yazmak öğrenilebilir; sabırlı ve kararlı olun!",
    "Bir kodu anlamadıysanız, o kod yeterince açık yazılmamıştır.",
    "Kod yazmayı bırakmadığın sürece, buglar seni asla yenemez.",
    "Bugün çözemediğin hata, yarının en büyük öğrenimidir.",
    "Kod yazmak bir sanat, debug yapmak bir bilimdir.",
    "Her return bir fırsattır, her break bir mola.",
  ],
  en: [
    "Write small, testable pieces of code.",
    "Learn something new every day to become a better developer.",
    "Software is not just about coding; it's the art of problem-solving.",
    "Document every piece of code carefully.",
    "Success comes with small steps every day.",
    "Remember: Code is meant to be rewritten, not worshipped!",
    "Finding a bug is the start of crafting a solution.",
    "Got a problem? First, Google it, then ask your mentors!",
    "Coding is a learnable skill; be patient and determined.",
    "If you can't understand a code, it wasn't written clearly enough.",
    "Keep coding, and bugs will never defeat you.",
    "Today's unresolved bug is tomorrow's greatest lesson.",
    "Writing code is an art; debugging is a science.",
    "Every return is an opportunity, every break is a pause.",
  ],
};
