export const tips = [
  "Kod yazarken küçük ve test edilebilir parçalar oluşturun.",
  "Daha iyi bir geliştirici olmak için her gün bir şey öğrenin.",
  "Yazılım sadece kod yazmak değildir; problem çözme sanatıdır.",
  "Her kod parçasını belgelendirmeye özen gösterin.",
  "Başarı, her gün atılan küçük adımlarla gelir.",
  "Hatırlayın: Kod tekrar yazılmak için vardır, kutsal değildir!",
  "Bir hata bulmak, bir çözüm üretmenin başlangıcıdır.",
  "Bir problem mi var? Önce Google, sonra mentorlar!",
  "Kod yazmak öğrenilebilir; sabırlı ve kararlı olun!",
  "Bir kodu anlamadıysanız, o kod yeterince açık yazılmamıştır.",
  "Kullanıcı arayüzü, kaotik karmaşıklıktan zarif sadeliğe geçiş sürecidir.",
  "Programlama, kendinize ölünceye kadar ‘Bir saat içinde bir toplantım var, bu yüzden buna henüz başlamayayım’ demektir.",
  "Bir yazılımdaki ilerlemeyi, yazılmış kodun satır sayısıyla değerlendirmek, uçak yapımındaki ilerlemeyi uçağın ağırlığıyla değerlendirmek gibidir.",
  "Hata yapmaktan korkma; en iyi çözümler genellikle bir hatanın ardında saklıdır.",
  "Bugün bir satır kod bile yazdıysan, yarından daha iyi bir yazılımcısın.",
  "Kodun karmaşık değil, çözümün basit olmalı.",
  "Her ‘ben bunu yapamam’ düşüncesi, yeni bir dil öğrenerek bozulabilir.",
  "Kod yazmayı bırakmadığın sürece, buglar seni asla yenemez.",
  "Yazılımcıların kahvesi biterse, buglar çoğalır.",
  "Kod yazarken zaman hızlı, deploy sırasında yavaş akar.",
  "Yazılım projelerinde %90 tamamlanması, projenin %50 daha işi olduğu anlamına gelir.",
  "Yazılım geliştirme: 'Bu çalışmıyor' ile 'Nasıl çalışıyor anlamıyorum' arasında bir yolculuk.",
  "‘Hello World’ her dilde güzeldir, ama hata mesajları herkesin ortak dili.",
  "Kod bir araçtır, asıl sihir fikirdedir.",
  "Her hatanın bir hikayesi vardır; yazılımcılar hikaye anlatıcılarıdır.",
  "Bugün çözemediğin hata, yarının en büyük öğrenimidir.",
  "Kod yazmak bir sanat, debug yapmak bir bilimdir.",
  "Her `return` bir fırsattır, her `break` bir mola.",
];
